<a href="https://colab.research.google.com/github/bmukhammadaliev/Data-Science-and-AI/blob/main/mohirdev_NumPy_extra_mashq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini 
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

In [4]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.8/dist-packages/numpy/version.py'>

In [6]:
np.__config__.show

<function numpy.__config__.show()>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring! 

`💡Ishora` numpy.array

In [7]:
data = [1,2,3,4,5,6,7,8]
array = np.array(data)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [12]:
arr = np.zeros(shape = (9,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [18]:
#arr.size
arr.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin? 


`💡Ishora` np.info

In [20]:
np.add?

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [23]:
arr1 = np.zeros(shape = 12)
arr1[5] = 1
arr1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [24]:
arr2 = np.arange(20,60,1)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring 
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [26]:
arr3 = arr2[::-1]
arr3

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [27]:
arr4 = np.arange(12,21,1).reshape(3,3)
arr4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0] 





`💡Ishora` np.nonzero

In [31]:
arr5 = np.array([3, 7, 0, 0, 9, 0])
index = np.where(arr5 != 0)
index


(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [32]:
arr6 = np.random.randn(2,2,2)
arr6

array([[[-0.55342346, -0.51561029],
        [-0.19950504, -1.50773689]],

       [[ 1.84424872, -1.66505201],
        [ 0.58801772, -0.13404605]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [34]:
arr7 = np.random.rand(9,9)
arr7

array([[0.59904   , 0.78473536, 0.00500027, 0.73382796, 0.30054297,
        0.21592876, 0.08270757, 0.44110371, 0.1315027 ],
       [0.3283138 , 0.78095255, 0.80123565, 0.13780594, 0.84812681,
        0.78546908, 0.0764113 , 0.48052044, 0.31764305],
       [0.01528752, 0.83813641, 0.95292332, 0.29523602, 0.9526025 ,
        0.88777125, 0.03447392, 0.78651617, 0.85148848],
       [0.25465795, 0.2302037 , 0.27731959, 0.91186664, 0.41916873,
        0.78339263, 0.47709446, 0.47572597, 0.7906719 ],
       [0.70596262, 0.42269308, 0.35248254, 0.45183477, 0.76289026,
        0.89676558, 0.25978558, 0.66991943, 0.3905114 ],
       [0.11890624, 0.17853211, 0.55304409, 0.49079712, 0.93386383,
        0.63138477, 0.88150302, 0.05285052, 0.8857931 ],
       [0.08104322, 0.63001038, 0.61784328, 0.09999241, 0.38634125,
        0.9064926 , 0.5227618 , 0.94923518, 0.94120254],
       [0.70991247, 0.70808001, 0.86734571, 0.76507438, 0.78182038,
        0.92924366, 0.98637445, 0.76455321, 0.10957179],


In [36]:
min = np.min(arr7)
max = np.max(arr7)
min, max

(0.005000272002582018, 0.9863744546554759)

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [37]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [45]:
arr8 = np.random.randn(6,3)
arr9 = np.random.randn(3,4)
result = np.dot(arr8, arr9)
result

array([[ 1.71131804,  0.21174627,  0.49124285,  2.63285276],
       [-0.80256343, -0.02804735,  0.30434341,  2.58473474],
       [-2.26300615, -0.44913451, -0.9602216 , -0.73630219],
       [ 1.46018867, -0.06996425, -0.32814228,  2.77887679],
       [-0.70890158,  0.43363438,  1.74890259,  2.70531995],
       [ 1.54441798,  1.38232212,  4.33771591,  4.06760464]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [100]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

In [47]:
arr10 = np.random.randn(3,5)
arr10

array([[-0.54939321, -0.55124517, -1.07059876, -0.06101325,  0.07469144],
       [-0.47666632,  2.97318823, -0.31087166,  0.16696176,  0.4448241 ],
       [ 3.40467209, -1.137044  , -0.30154106, -1.3632864 ,  0.0189918 ]])

In [48]:
arr11 = np.random.randn(3,5)
arr11

array([[-1.49600459,  1.13663112,  0.40219211, -0.02194723, -0.08288263],
       [ 0.36332779, -0.40457078, -0.09931567,  1.15956882, -0.34388457],
       [ 0.94075891,  0.33532153, -1.7869463 ,  0.85187849,  0.44636416]])

In [49]:
arr10>arr11

array([[ True, False, False, False,  True],
       [False,  True, False, False,  True],
       [ True, False,  True, False, False]])

In [50]:
arr10<arr11

array([[False,  True,  True,  True, False],
       [ True, False,  True,  True, False],
       [False,  True, False,  True,  True]])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [51]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-51-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-51-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [52]:
arr13 = np.array([1, 2, 3, 4, 5])
arr14 = np.array([3, 4, 5, 6, 7])

result = np.intersect1d(arr13, arr14)
result

array([3, 4, 5])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [201]:
# Create an array of random floating point numbers
arr = np.array([10, -87.24536, 56.7, -746, 0.674])
print("Original array:", arr)

# Use the modulo operator to extract the positive part of the numbers
positive_part = arr[arr>0] 
print("Positive part using modulo operator:", positive_part, 'chala')

# Use the numpy floor function to extract the positive part of the numbers
positive_part = np.floor(arr[arr>0])
print("Positive part using numpy floor:", positive_part)

# Use the astype method to change the data type to int and then extract the positive part of the numbers
positive_part = arr[arr>0].astype(int)
print("Positive part using astype:", positive_part)

# Use the numpy trunc function to extract the positive part of the numbers
positive_part = np.trunc(arr[arr>0])
print("Positive part using numpy trunc:", positive_part)

Original array: [ 1.000000e+01 -8.724536e+01  5.670000e+01 -7.460000e+02  6.740000e-01]
Positive part using modulo operator: [10.    56.7    0.674] chala
Positive part using numpy floor: [10. 56.  0.]
Positive part using astype: [10 56  0]
Positive part using numpy trunc: [10. 56.  0.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [78]:
arr17 = np.arange(0, 2.25, 0.25).reshape(3,3)
arr17

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

In [82]:
#alternatives:

#1
arr = np.random.randint(0, 3, size=(3,3))
print(arr)

#2
arr1 = np.floor(np.random.rand(3,3) * 3)
print(arr1)

#3
arr2 = np.linspace(0,2,9).reshape(3,3)
print(arr2)

[[2 1 1]
 [1 1 2]
 [1 0 2]]
[[1. 0. 0.]
 [1. 1. 0.]
 [0. 2. 0.]]
[[0.   0.25 0.5 ]
 [0.75 1.   1.25]
 [1.5  1.75 2.  ]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [84]:
arr19 = np.random.randn(10)
sorted = np.sort(arr19)
sorted

array([-0.99139196, -0.47516276,  0.02678973,  0.40768823,  0.73568704,
        0.74785064,  1.16590594,  1.33829761,  1.97349546,  2.06605409])

#### 22. A va B nomi bilan ikkita tasodifiy qiymatlardan iborat bo'lgan massiv yarating, so'ng ulardan qaysi biri katta yoki kichik ekanligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [89]:
A = np.random.randn(9)
B = np.random.randn(9)

rslt = np.array_equal(A, B)
print(rslt)

rslt1 = np.allclose(A, B)
print(rslt1)

rslt2 = np.greater(A, B)
print(rslt2)

False
False
[ True False  True  True False False  True False False]


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring. 


`💡Ishora` np.dot or np.ones

In [93]:
x = np.ones(shape = (6,3))
y = np.ones(shape = (3, 4))

xy = np.dot(x, y)
xy

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [98]:
t = np.random.randn(6)
print(t)
t[np.argmax(t)] = 0
t

[-1.56143993  0.61102444  0.2811642  -0.18952171  0.77419905 -1.72775548]


array([-1.56143993,  0.61102444,  0.2811642 , -0.18952171,  0.        ,
       -1.72775548])

#### 25. Quyidagi dastur qanday natija beradi?
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [99]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 26. NumPy kutubxonasi yordamida ikkita massivni solishtiruvchi dastur tuzing.
```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

In [103]:
print('Tepadagi savol yana qaytarilgan')

Tepadagi savol yana qaytarilgan


#### 27. Ikkita umumiy qiymatlari mavjud bo'lgan massiv yarating, so'ng ulardagi umumiy qiymatlarni aniqlovchi dastur tuzing.


`💡Ishora` np.intersect1d

In [104]:
print('Tepadagi savol yana qaytarilgan')

Tepadagi savol yana qaytarilgan


#### 28. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [122]:
hozir = np.datetime64('now')
print('Hozir:', hozir)

bugun = np.datetime64('today', 'D')
print('Bugun:', bugun)

ertaga = bugun + np.timedelta64(1, 'D')
print('Ertaga:', ertaga)

kecha = bugun - np.timedelta64(1, 'D')
print('Kecha:', kecha)

Hozir: 2023-01-28T23:34:31
Bugun: 2023-01-28
Ertaga: 2023-01-29
Kecha: 2023-01-27


#### 29. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [130]:
oy2016 = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
oy2016

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 30. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [131]:
print('Tepadagi savol yana qaytarilgan')

Tepadagi savol yana qaytarilgan


#### 31. Qator qiymatlari 0 dan 2 gacha bo'lgan 3x3 matritsa yarating.


`💡Ishora` np.arange

In [132]:
print('Tepadagi savol yana qaytarilgan')

Tepadagi savol yana qaytarilgan


#### 32. Tasodifiy qiymatlardan tashkil topgan 10 o'lchovli vektor yarating, so'ng uning qiymatlarini o'sish tartibida yozing.


`💡Ishora` sort

In [133]:
print('Tepadagi savol yana qaytarilgan')

Tepadagi savol yana qaytarilgan


#### 33. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [151]:
nums = np.random.rand(5, 10)
sum = np.add.reduce(nums)
print(sum)
sum1 = np.sum(nums, axis = 0)
print(sum1)

[1.56893791 1.77013762 2.8155082  2.61259047 2.15302931 2.87923007
 1.96430926 2.70594874 1.45795975 2.76140836]
[1.56893791 1.77013762 2.8155082  2.61259047 2.15302931 2.87923007
 1.96430926 2.70594874 1.45795975 2.76140836]


#### 34. Tasodifiy qiymatlardan tashkil topgan 5 o'lchovli vektor yarating, so'ng uning eng katta qiymatini 0 raqamiga almashtiring.


`💡Ishora` argmax

In [152]:
print('Tepadagi savol yana qaytarilgan')

Tepadagi savol yana qaytarilgan


#### 35. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [200]:
array = np.array([1, 2, 3, 4, 5])
result = np.repeat(array, 4)
result[1::4] = 0
print(result)
print('chala')

[1 0 1 1 2 0 2 2 3 0 3 3 4 0 4 4 5 0 5 5]
chala


#### 36. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 


`💡Ishora` stride_tricks.as_strided

In [198]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
shape = (11,4)
new = a.strides + a.strides
b = stride_tricks.as_strided(a, shape, new)
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 37. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [203]:
print('Bilmadim')

Bilmadim


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [204]:
print('Afsuski yoq')

Afsuski yoq
